vich_uploader:
    db_driver: orm

    mappings:
        image_bien:
            uri_prefix:         /upload/img/image_bien
            upload_destination: '%kernel.project_dir%/public/upload/img/image_bien'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
