#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /
    controller: App\Controller\HomeController::home

buy:
    path: /buy
    controller: App\Controller\BuyController::buyHome

show:
    path: /show/{id}
    controller: App\Controller\ShowController::showHome

sell:
    path: /sell
    controller: App\Controller\SellController::sellHome
