#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /
    controller: App\Controller\HomeController::home

buy:
    path: /buy
    controller: App\Controller\HomeController::buyHome

show:
    path: /show/{id}
    controller: App\Controller\HomeController::showBienById

sell:
    path: /sell
    controller: App\Controller\SellController::sellHome

admin:
    path: /admin
    controller: App\Controller\AdminProprieteController::index

add:
    path: /admin/add
    controller: App\Controller\AdminProprieteController::addBien

edit:
    path: /admin/edit/{id}
    controller: App\Controller\AdminProprieteController::editBien
    methods: [GET, POST]

delete:
    path: /admin/delete/{id}
    controller: App\Controller\AdminProprieteController::deleteBien
    methods: [POST, DELETE]